### ISSUE TITLE
Creating and collecting data 1.b.1.b.1.b 

### ISSUE THREAD

**Issue by nirupamaBenis** [ejp-rd-vp/smart-guidance#23]
**Chapter**: Creating and collecting data
**Question**: 1.b.1.b.1.b 
**Suggestion**: Add information
Molgenis https://www.molgenis.org/
OSSE https://bitbucket.org/medicalinformatics/samply.edc.osse/wiki/Home
Castor https://www.castoredc.com/

**Comment by pabloalarconm** [comment]
Done
