### ISSUE TITLE
Interpreting data 1

### ISSUE THREAD

**Issue by nirupamaBenis** [ejp-rd-vp/smart-guidance#28]
**Chapter**: Interpreting data
**Question**: 1
**Suggestion**: Edit/add information
A data model is a schema that establishes the data elements collected with or without the relationships between those elements. A semantic data model builds on a data model by assigning ontological concepts to the data elements and requiring relationships between the data elements where ever applicable. Thus a semantic data model explicitly describes the semantics underlying the data model. A semantic data model is recommended by the EJP RD because it is more machine-readable and thus more interoperable with other resources than a data model.

**Comment by pabloalarconm** [comment]
Done
