### ISSUE TITLE
Re-using data - 1.b.1.Yes - logic: why subquestion only about metadata

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/smart-guidance#60]
The question 1.b.1 is:

> Will you be using data that needs to be (re-)made computer readable first?

After clicking Yes, the subquestion is only related to metadata:

> Will you provide machine readable metadata, following a semantic metadata model, to others?

We may either need another subquestion for data or simply say data-related question will be asked in the next chapter.

**Comment by PhilipvD** [comment]
I reused this structure/question from the Life Sciences KM. In the context of reusable data, I think it makes sense to only ask whether machine readable metadata will be provide to others. 

I added the sentence "Note: machine-readable **data** will be covered in the next chapter."
