### ISSUE TITLE
Giving access to data - 2.b No - Text may not be correct

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/smart-guidance#63]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/47214182/155710388-7e23c3b1-bf79-4e5a-a868-4f9b3c29e232.png">

Can FAIRification stewards specify this?

**Comment by PhilipvD** [comment]
It should relate to the 'setup data access conditions' and 'make data access conditions machine readable' steps, is that not something the FAIRification stewards assist with? 

@brunasv Maybe you would be able to clarify this? Should we rephrase the advice?
