### ISSUE TITLE
Re-using data 1.b.1.b.1 - Confusion on tags and text

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/smart-guidance#64]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/47214182/155714014-b75dceca-8e50-4673-bbe4-fc2e71ffe2ec.png">

**Comment:**
There is no interpretation of colors. So the first time I saw this, I wondered how both ways can improve reusability?
Shall we just keep the green one?

<img width="467" alt="image" src="https://user-images.githubusercontent.com/47214182/155714035-5e83a435-75fc-47d4-ad1e-d381fbec1cfe.png">

**Comment:**
In the text below answers: is "already mostly" correct?

**Comment by hbcesar** [comment]
Shuxin I think your screenshot is not the correct one here. But I also do have a comment about this question (1.b.1.b): I wonder if an interpretation of “computer readable” should be provided? I mean, what do we consider computer readable?

**Comment by sxzhang1201** [comment]
Thanks @hbcesar ! Just correct it.

**Comment by PhilipvD** [comment]
"There is no interpretation of colors. So the first time I saw this, I wondered how both ways can improve reusability?
Shall we just keep the green one?"
Fixed! This had to do with the metrics, which we do not use. 

Other two comments need further discussion
