### ISSUE TITLE
Re-using data - 1.b.2 - Logic: jump from data to data element?

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/smart-guidance#65]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/47214182/155711463-36899fc6-c0e4-4d62-b87c-8c1649e92afc.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/47214182/155711493-1611046c-6deb-45a7-913c-7bbbb93f7579.png">

**Here is comment:**
Is it too jumping from data to data elements?

**Comment by PhilipvD** [comment]
I agree, this question also seems redundant with the ones around the CDEs asked under 'Interpreting data'. In addition to that, the question is rather vague: 'are your data elements compliant with the CDEs' -> the meaning of 'compliant' is not clear. 

We could remove it?
