### ISSUE TITLE
Processing data 1.a.1.a

### ISSUE THREAD

**Issue by hbcesar** [ejp-rd-vp/smart-guidance#68]
There is no text for 1.a.1.a "Yes" option.

**Comment by sxzhang1201** [comment]
Is it the same: https://github.com/ejp-rd-vp/smart-guidance/issues/25?

**Comment by sxzhang1201** [comment]
I think you should test on the next version (probably 0.3.0) because Pablo already made some improvement yesterday based on Niru's comments :) though I have read all closed comments, which was not that easy and fun.

**Comment by PhilipvD** [comment]
This was indeed fixed with the other issue.
